### ISSUE TITLE
이제 해야되는것들

### ISSUE THREAD

**Issue by yugd1211** [42daechoi/trenscendence#40]
1. [x] (intra: , branch: ) 게임 초대 
2. [x] (intra: , branch: ) 채팅 폴링에 다른 모달창도 리렌더링 되면서 close 되는 현상
3. [x] (intra: , branch: ) channel-list 검색창 추가(search-side를 list 자식으로 수정)
5. [x] (intra: , branch: ) 채팅방 제목 수정
6. [x] (intra: gyyu, branch: 39-gamelog-leaderboard )   게임 로그, 리더보드(api로 초기화)
7. [x] (intra: , branch: ) 채팅 프로필 설정(친구창이랑 같게 자신의 모달은 아무것도 안뜨게)
8. [x] (intra: , branch: ) 닉네임 수정 글자 제한
9. [x] (intra: , branch: ) 채팅방에 더미 유저(다른 페이지 갔다 되돌아오면 생김)

**Comment by 42daechoi** [comment]
닉네임 수정 글자 제한 - 13글자 제한)
채팅방 제목 수정 - 채팅방 제목 최초에 띄워주기에 최상단 채팅방 제목 삭제
 채팅 폴링에 다른 모달창도 리렌더링 되면서 close 되는 현상 - 수정 완료
